# Default values for sonarQube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

sonarqube:
 image: sonarqube
 tag: latest
 replicaCount: 1
 port: 9000
 resources:
  limit:
    cpu: 2000m
    memory: 2048Mi
  request:
    cpu: 500m
    memory: 1024Mi
 env:
   SONARQUBE_JDBC_USERNAME: sonarqube
   SONARQUBE_JDBC_URL: "jdbc:postgresql://postgresdb:5432/sonardb"
   SONARQUBE_JDBC_PASSWORD: yourpassword
 perstisted: true
 storage_access_mode: ReadWriteMany
 data_storage_size: 500mi
 extensions_storage_size: 200mi
 persistance_sever: 192.168.56.108 

postgres:
  image: postgres
  tag: latest
  perstisted: true
  storage_access_mode: ReadWriteMany
  storage_size: 500mi
  persistance_sever: 192.168.56.108 
  replicaCount: 1
  port: 5432
  persistance_path: /var/lib/postgresql/data/
  env:
    POSTGRES_USER: sonarqube
    POSTGRES_PASSWORD: "yourpassword"
    POSTGRES_DB: "sonardb"
    PGDATA: /var/lib/postgresql/data/sonardb
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
