apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: default
spec:
  releaseName: jenkins
  helmVersion: v3
  chart:
    git: git@github.com:OmarCherdal1997/helm.git
    ref: main
    path: jenkins
  values:
    replicaCount: 1
    image_tag: "lts-jdk11"
    image_name: "jenkins"
    image_http_port: 8080
    image_jnlp_port: 50000
    replicaCount: 2

