{{ if eq .Values.redisBackup.isBackuped true }}
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backup
  annotations:
     "helm.sh/hook": pre-upgrade
     "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: {{ .Values.redisBackup.volumeSize }} 
{{ end }}
