apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
  name: svc-{{ .Release.Name }}
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}
