{{ if eq .Values.plugins.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-plugins-config
  namespace: {{ .Release.Name }}
data:
  required_plugins.txt: |
     configuration-as-code:latest
     credentials:latest
     eiffel-broadcaster:latest
     envinject-api:latest
     envinject:latest
     job-dsl:latest
     ldap:latest
     locale:latest
     mailer:latest
     matrix-auth:latest
     matrix-project:latest
     pam-auth:latest
     active-directory:latest
     artifactory:latest
     build-failure-analyzer:latest
     cloudbees-folder:latest
     kubernetes:latest

{{ end }}