{{- $relname := .Release.Name -}}

{{ with .Values.persistance }}
{{ if eq .isenabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $relname }}-home
spec:
  accessModes:
  - {{ .storage_access_mode }}
  capacity:
    storage: {{ .storage_size }}
  nfs:
    path: /nfsroot/{{ .Release.Name }}_home
    server: {{ .persistance_sever }}

{{ end }}

{{ end }}
