apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-home
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 900Mi
  nfs:
    path: /nfsroot/{{ .Release.Name }}_home
    server: 192.168.56.108
