{{- $relname := .Release.Name -}}
{{ with .Values.persistance }}
{{ if eq .isenabled true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $relname }}-home
  namespace: {{ $relname }}
spec:
  accessModes:
  - {{ .storage_access_mode }}
  resources:
    requests:
      storage: {{ .storage_size }}

{{ end }}

{{ end }}
