apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - watch
  - list
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
