apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: redisinsight-{{ .Release.Name }}
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: redisinsight-{{ .Release.Name }}-svc
            port:
              number: 80
        path: /redisinsight-{{ .Release.Name }}
        pathType: Prefix
status:
  loadBalancer: {}
