apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redisinsight-{{ .Release.Name }}
  name: redisinsight-{{ .Release.Name }}-svc
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.redisinsight_port }}
  selector:
    app: redisinsight-{{ .Release.Name }}
status:
  loadBalancer: {}
