apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  namespace: {{ .Release.Name }}
  labels:
    app: postgresdb
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: {{ .Values.postgres.port }}
  selector:
    app: postgresdb