apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: {{ .Release.Name }}
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
  - name: sonarqube
    protocol: TCP
    port: {{ .Values.postgres.port }}
  selector:
    app: sonarqube